WebMVC/Models/Hotel.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.Models
{
    public class Hotel
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }
        [BsonElement("Name")]
        public string Name { get; set; }
        [BsonElement("City")]
        public string City { get; set; }
        [BsonElement("Address")]
        public string Address { get; set; }
        [BsonElement("Rate")]
        public decimal Rate { get; set; }
        [BsonElement("Rooms")]
        public List<Room> Rooms { get; set; }
        [BsonElement("OwnerID")]
        public string OwnerID { get; set; }

        internal Task ToListAsync()
        {
            throw new NotImplementedException();
        }
    }
}

WebMVC/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebMVC.Helper;
using WebMVC.Models;
using WebMVC.Services;

namespace WebMVC.Controllers
{
    public class ReservationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private readonly IReservationService _reservationService;
        private readonly IHotelService _hotelService;
        private readonly IHttpContextAccessor _accessor;
        private readonly IServiceProvider _serviceProvider;

        public ReservationController(IReservationService reservationService, IHotelService hotelService, IHttpContextAccessor accessor, IServiceProvider serviceProvider)
        {
            _reservationService = reservationService;
            _hotelService = hotelService;
            _accessor = accessor;
            _serviceProvider = serviceProvider;
        }

        // POST: ReservationController/Create
        [HttpGet]
        public async Task<ActionResult> Create(string hotelId, string roomId, DateTime startDate, DateTime endDate)
        {
            var user = UserStorage.users.SingleOrDefault(u => u.Id == _accessor.HttpContext.Session.GetString("ID"));

            if (user == null)
            {
                return RedirectToAction("Index", "Authorize");
            }

            if (user.ExpiresTime < DateTime.Now)
            {
                using (var scope = _serviceProvider.CreateScope())
                {
                    var authorizeService = scope.ServiceProvider.GetRequiredService<IAuthorizeService>();
                    await authorizeService.RefreshToken();
                }
            }

            RoomHotelViewModel room = await _hotelService.GetRoom(hotelId, roomId);

            Reservation reservation = new Reservation
            {
                HotelId = hotelId,
                RoomId = room.Room.Id,
                UserId = _accessor.HttpContext.Session.GetString("ID"),
                StartDate = startDate,
                EndDate = endDate,
                Price = room.Room.Price
            };
            var res = await _reservationService.CreateReservationAsync(reservation);

            return RedirectToAction("GetUsersReservations");
        }

        // POST: ReservationController/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            var user = UserStorage.users.SingleOrDefault(u => u.Id == _accessor.HttpContext.Session.GetString("ID"));

            if (user == null)
            {
                return RedirectToAction("Index", "Authorize");
            }

            if (user.ExpiresTime < DateTime.Now)
            {
                using (var scope = _serviceProvider.CreateScope())
                {
                    var authorizeService = scope.ServiceProvider.GetRequiredService<IAuthorizeService>();
                    await authorizeService.RefreshToken();
                }
            }

            ViewBag.error = "";
            if (string.IsNullOrEmpty(id))
            {
                ViewBag.error = $"No reservation found for id {id}";
            }

            var res = await _reservationService.DeleteReservationAsync(id);

            if (!res)
            {
                ViewBag.error = $"No reservation found for id {id}";
            }

            return RedirectToAction("GetUsersReservations");
        }

        [HttpGet]
        public async Task<ActionResult<Reservation>> Details(string id)
        {
            var user = UserStorage.users.SingleOrDefault(u => u.Id == _accessor.HttpContext.Session.GetString("ID"));

            if (user == null)
            {
                return RedirectToAction("Index", "Authorize");
            }

            if (user.ExpiresTime < DateTime.Now)
            {
                using (var scope = _serviceProvider.CreateScope())
                {
                    var authorizeService = scope.ServiceProvider.GetRequiredService<IAuthorizeService>();
                    await authorizeService.RefreshToken();
                }
            }

            if (string.IsNullOrEmpty(id))
            {
                return BadRequest("Need valid reservation id");
            }

            var res = await _reservationService.GetReservationAsync(id);

            if (res == null)
            {
                return BadRequest($"No reservation found for id {id}");
            }

            return View("ReservationDetails", res);
        }

        [HttpGet]
        public async Task<ActionResult<List<Reservation>>> GetAllReservations()
        {
            var user = UserStorage.users.SingleOrDefault(u => u.Id == _accessor.HttpContext.Session.GetString("ID"));

            if (user == null)
            {
                return RedirectToAction("Index", "Authorize");
            }

            if (user.ExpiresTime < DateTime.Now)
            {
                using (var scope = _serviceProvider.CreateScope())
                {
                    var authorizeService = scope.ServiceProvider.GetRequiredService<IAuthorizeService>();
                    await authorizeService.RefreshToken();
                }
            }

            var res = await _reservationService.GetAllReservationsAsync();
            ViewBag.empty = "";
            if (res == null)
            {
                ViewBag.empty = "0 reservations";
            }

            return View("ListRes",res);
        }

        [HttpGet]
        public async Task<ActionResult<List<Reservation>>> GetUsersReservations()
        {
            var user = UserStorage.users.SingleOrDefault(u => u.Id == _accessor.HttpContext.Session.GetString("ID"));

            if (user == null)
            {
                return RedirectToAction("Index", "Authorize");
            }

            if (user.ExpiresTime < DateTime.Now)
            {
                using (var scope = _serviceProvider.CreateScope())
                {
                    var authorizeService = scope.ServiceProvider.GetRequiredService<IAuthorizeService>();
                    await authorizeService.RefreshToken();
                }
            }

            var res = await _reservationService.GetUsersReservations();
            @ViewBag.empty = "";
            if (res.Count == 0)
            {
                @ViewBag.empty = "You don't have any reservations";
            }

            return View("ListRes", res);
        }

        [HttpGet]
        public async Task<ActionResult<List<Reservation>>> GetOwnersReservations(string id)
        {
            var user = UserStorage.users.SingleOrDefault(u => u.Id == _accessor.HttpContext.Session.GetString("ID"));

            if (user == null)
            {
                return RedirectToAction("Index", "Authorize");
            }

            if (user.ExpiresTime < DateTime.Now)
            {
                using (var scope = _serviceProvider.CreateScope())
                {
                    var authorizeService = scope.ServiceProvider.GetRequiredService<IAuthorizeService>();
                    await authorizeService.RefreshToken();
                }
            }

            var res = await _reservationService.GetOwnersReservations(id);
            @ViewBag.empty = "";
            if (res.Count == 0)
            {
                @ViewBag.empty = "You don't have any reservations for this hotel";
            }

            return View("ListRes", res);
        }

        [HttpGet("Reservation/{id:length(24)}")]
        public async Task<ActionResult<List<Reservation>>> GetUsersReservations(string id)
        {
            var user = UserStorage.users.SingleOrDefault(u => u.Id == _accessor.HttpContext.Session.GetString("ID"));

            if (user == null)
            {
                return RedirectToAction("Index", "Authorize");
            }

            if (user.ExpiresTime < DateTime.Now)
            {
                using (var scope = _serviceProvider.CreateScope())
                {
                    var authorizeService = scope.ServiceProvider.GetRequiredService<IAuthorizeService>();
                    await authorizeService.RefreshToken();
                }
            }

            var res = await _reservationService.GetUsersReservations(id);
            @ViewBag.empty = "";
            if (res.Count == 0)
            {
                @ViewBag.empty = "User don't have any reservations";
            }

            return View("ListRes", res);
        }
    }
}

WebMVC/Views/Hotel/HotelCreate.cshtml
@model WebMVC.Models.Hotel
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "HotelCreate";
}

<h1>HotelCreate</h1>
@ViewBag.createHotel
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateHotel" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"  required/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" required/>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" required/>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to list", "GetOwnerHotel", "Hotel", new { ownerId = @HttpContextAccessor.HttpContext.Session.GetString("ID") })
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMVC/Views/Hotel/HotelDetails.cshtml
@model WebMVC.Models.Hotel
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "HotelDetails";
}

<div>
    <h1>Hotel</h1>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rate)
        </dd>
    </dl>
    @if (@HttpContextAccessor.HttpContext.Session.GetString("Role") != null)
    {
        @if (@HttpContextAccessor.HttpContext.Session.GetString("Role") == "Owner" && Model.OwnerID == @HttpContextAccessor.HttpContext.Session.GetString("ID"))
        {
            @Html.ActionLink("Edit", "EditHotel", new { id = Model.Id }, new { @class = "btn btn-primary" })
        }
    }

    @if (@HttpContextAccessor.HttpContext.Session.GetString("ID") != null)
    {
        @if (@HttpContextAccessor.HttpContext.Session.GetString("ID") == Model.OwnerID)
            @Html.ActionLink("Add room", "CreateRoom", new { hotelId = Model.Id }, new { @class = "btn btn-primary" })
    }
    @if (Model.Rooms == null)
    {
        <p>There are no rooms</p>
    }
    else
    {
        <h3>Rooms</h3>

        @foreach (var item in Model.Rooms)
        {
            <dl class="row">
                @if (@HttpContextAccessor.HttpContext.Session.GetString("Role") != null)
                {
                    @if (@HttpContextAccessor.HttpContext.Session.GetString("Role") == "Owner" && Model.OwnerID == @HttpContextAccessor.HttpContext.Session.GetString("ID"))
                    {
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(i => item.Id)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(i => item.Id)
                        </dd>
                    }
                }
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(i => item.BedForOne)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(i => item.BedForOne)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(i => item.BedForTwo)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(i => item.BedForTwo)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(i => item.NumberOfGuests)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(i => item.NumberOfGuests)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(i => item.Price)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(i => item.Price)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(i => item.Standard)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(i => item.Standard)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(i => item.Description)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(i => item.Description)
                </dd>
                @if (@HttpContextAccessor.HttpContext.Session.GetString("Role") != null)
                {
                    @if (@HttpContextAccessor.HttpContext.Session.GetString("Role") == "Owner" && Model.OwnerID == @HttpContextAccessor.HttpContext.Session.GetString("ID"))
                    {
                        <dt class="col-sm-2">
                            Delete
                        </dt>
                        <dd class="col-sm-10">
                            @Html.ActionLink("Delete", "DeleteRoom", new { hotelId = Model.Id, roomId = item.Id }, new { @class = "btn btn-primary" })
                        </dd>
                    }
                }
            </dl>
        }
    }

</div>
<div>
    @if (@HttpContextAccessor.HttpContext.Session.GetString("Role") != null)
    {
        @if (@HttpContextAccessor.HttpContext.Session.GetString("Role") == "Owner" && Model.OwnerID == @HttpContextAccessor.HttpContext.Session.GetString("ID"))
        {
            @Html.ActionLink("Back to list", "GetOwnerHotel", new { ownerId = @HttpContextAccessor.HttpContext.Session.GetString("ID") })
        }
        else
        {
            @Html.ActionLink("Back to list", "GetHotels")
        }
    }
    else
    {
        @Html.ActionLink("Back to list", "GetHotels")
    }
</div>

WebMVC/Views/Hotel/HotelEdit.cshtml
@model WebMVC.Models.Hotel

@{
    ViewData["Title"] = "HotelEdit";
}

<h1>HotelEdit</h1>

<h4>Hotel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditHotel" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rate" class="control-label"></label>
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerID" class="control-label"></label>
                <input asp-for="OwnerID" class="form-control" />
                <span asp-validation-for="OwnerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to list", "GetHotels")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMVC/Views/Hotel/HotelList.cshtml
@model IEnumerable<WebMVC.Models.Hotel>

@{
    ViewData["Title"] = "ListHotels";
}

<h1>ListHotels</h1>


@if (@ViewBag.empty == "")
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Rate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OwnerID)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.HiddenFor(modelItem => item.Id)
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Rate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OwnerID)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "EditHotel", new { id=item.Id }) |
                        @Html.ActionLink("Details", "GetHotel", new { id=item.Id }) |
                        @Html.ActionLink("Delete", "DeleteHotel", "Hotel", new { id=item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>@ViewBag.empty</h3>
}

WebMVC/Views/Hotel/HotelOwnerList.cshtml
@model IEnumerable<WebMVC.Models.Hotel>

@{
    ViewData["Title"] = "HotelOwnerList";
}

<h1>HotelOwnerList</h1>
@Html.ActionLink("Create New", "CreateHotel")
@if (@ViewBag.empty == "")
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Rate)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.HiddenFor(modelItem => item.Id)
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Rate)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "EditHotel", new { id = item.Id }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Details", "GetHotel", new { id = item.Id }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Delete", "DeleteHotel", "Hotel", new { id = item.Id }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Reservations", "GetOwnersReservations", "Reservation", new { id = item.Id }, new { @class = "btn btn-primary" })
                    </td>
                </tr>
            }
        </tbody>
    </table>

}
else
{
    <h3>@ViewBag.empty</h3>
}

WebMVC/Views/Hotel/ListHotels.cshtml
@model IEnumerable<WebMVC.Models.Hotel>

@{
    ViewData["Title"] = "ListHotels";
}

<h1>ListHotels</h1>


@if (@ViewBag.empty == "")
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Rate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OwnerID)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Rate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OwnerID)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>@ViewBag.empty</h3>
}

WebMVC/Views/Hotel/RoomList.cshtml
@model IEnumerable<WebMVC.Models.RoomHotelViewModel>
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "View";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<h1>Rooms</h1>

@using (Html.BeginForm("GetFiltredRooms", "Hotel", FormMethod.Get))
{

    <div class="form-inline card-header">
        @Html.TextBox("city", ViewBag.CurrentFilter as string, new { @class = "form-control col-md-2 ", @placeholder = "City" })
        @Html.TextBox("phrase", ViewBag.CurrentFilter as string, new { @class = "form-control col-md-2 float-left ml-3", @placeholder = "Phrase" })
        @Html.TextBox("bedForOne", ViewBag.CurrentFilter as string, new { @class = "form-control col-md-2 float-left ml-3", @placeholder = "Bed for one", @type = "number", @min = "0",  })
        @Html.TextBox("bedForTwo", ViewBag.CurrentFilter as string, new { @class = "form-control col-md-2 float-left ml-3", @placeholder = "Bed for two", @type = "number", @min = "0" })
        @Html.TextBox("numberOfGuests", ViewBag.CurrentFilter as string, new { @class = "form-control col-md-1 float-left ml-3", @placeholder = "Guests", @type = "number", @min = "0" })
        @Html.TextBox("price", ViewBag.CurrentFilter as string, new { @class = "form-control col-md-2 float-left ml-3", @placeholder = "Max price", @type = "number", @min = "0" })
    </div>
    <div class="form-inline card-header">
        @Html.DropDownList("standard", new SelectList(ViewBag.Standard), "Wybierz standard", new { @class = "form-control" })
        @Html.TextBox("dateStart", ViewBag.CurrentFilter as string, new { @class = "form-control col-md-2 float-left ml-3", @placeholder = "Data poczatkowa", @type = "date", min = DateTime.Now })
        @Html.TextBox("dateEnd", ViewBag.CurrentFilter as string, new { @class = "form-control col-md-2 float-left ml-3", @placeholder = "Data końcowa", @type = "date", @min = DateTime.Now })
        
        <input id="filter" class="btn btn-primary float-left ml-3" type="submit" value="Search" />
    </div>
}
<span class="text-danger">@ViewBag.error</span>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Room.BedForOne)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room.BedForTwo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room.NumberOfGuests)
            </th>
            <th>
                @Html.ActionLink("Price", "GetFiltredRooms", new { sortOrder = ViewBag.PriceSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room.Standard)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Room.BedForOne)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Room.BedForTwo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Room.NumberOfGuests)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Room.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Room.Standard)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Room.Description)
                </td>
                <td>
                    @Html.ActionLink("Details", "GetRoom", new { hotelId = item.HotelId, roomId = item.Room.Id, }, new { @class = "btn btn-primary" })
                    @if (@HttpContextAccessor.HttpContext.Session.GetString("Role") == "User" && ViewBag.error == "")
                    {
                        <button class="btn btn-success book-btn" onclick="book('@item.HotelId', '@item.Room.Id')">Book</button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<script>

    function book(hotelId, roomId) {
        if ($('#dateStart').val() != "" && $('#dateEnd').val() != "" && $('#dateStart').val() < $('#dateEnd').val()) {
            $.get('@Url.Action("Create", "Reservation")', { hotelId: hotelId, roomId: roomId, startDate: $('#dateStart').val(), endDate: $('#dateEnd').val() }, function (data) {
                window.location.replace('@Url.Action("GetUsersReservations", "Reservation")');
            });
        } else if ($('#dateStart').val() < $('#dateEnd').val()) {
            alert("end date must be later than start date");
        }
        else {
            $('#dateStart').select();
            alert("select a start date and end date");
        }
    }
    $("#dateEnd").change(function () {
        if ($("#dateStart").val() != "") {
            $("#filter").click();
        }
    });
    $("#dateStart").change(function () {
        if ($("#dateEnd").val() != "") {
            $("#filter").click();
        }
    });



    $(document).ready(function () {
        if ($('#dateStart').val() == "" || $('#dateEnd').val() == "" ) {
                $(".book-btn").hide();
            }

    });
</script>